name: Run tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: chmod +x test.sh && ./test.sh
